[package]
name = "ggway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
json = "0.12.4"
reqwest = { version = "0.12.4", features = ["blocking"] }
